# Site settings
title: IANAD
email: mog@rldn.net
description: > # this means to ignore newlines until "baseurl:"
  Matthew is a 6 foot tall ape descendent.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://mogorman.github.io" # the base hostname & protocol for your site
twitter_username: mogactually
github_username:  mogorman

# Build settings
markdown: kramdown
